### PR TITLE
Add py.typed for type checkers following PEP 561

### PR DESCRIPTION
**Pull request by Zocker1999NET**
While the `py.typed` file is missing, type checkers like mypy will treat the library as untyped when included into other projects. This behavior is defined in [PEP 561](https://peps.python.org/pep-0561/) Adding this file to the package (and ensure it gets packaged) does make the library accessible for type checkers.

To add it, I followed [this short guide](https://dev.to/whtsky/don-t-forget-py-typed-for-your-typed-python-package-2aa3).
To test it, I force-installed your package into a venv, wrote test code which uses this library, and verified that mypy now can type check everything (aka. following error is now missing: `Skipping analyzing "rss_parser": module is installed, but missing library stubs or py.typed marker  [import]`)

### CODE REVIEW

**Comment by dhvcc** [comment]
Hi, thanks for the PR, looks good to me

**Comment by dhvcc** [comment]
May be we can add a test with mypy to  somehow test this behavior?

**Review by dhvcc — APPROVED** [review]

**Comment by Zocker1999NET** [comment]
> May be we can add a test with mypy to somehow test this behavior?

I‘ve checked but did not find a way to test it with a simple command line parameter. Maybe they would implement one if asked? Otherwise, one could setup a test project importing this one and check if mypy raises an issue that it cannot find type hintings for the imported project.

However, sadly currently I have no time to look into this myself.

Thanks for merging :heart:

**Comment by dhvcc** [comment]
Creating a code with import is how I tested it, we could do that, but with no changes to this in near future I don't see a need
Thanks for the PR

**Pull request merged**
