### PR TITLE
Add documentation to methods

### PR DESCRIPTION
**Pull request by BBArikL**

### CODE REVIEW

**Comment by dhvcc** [comment]
Please, pull changes from master to fix CI

**Comment by dhvcc** [comment]
👋 is still WIP? If not I will review it and we'll try to figure out the CI issues

**Comment by BBArikL** [comment]
It is complete, all methods have their documentation and type annotations as far as I am aware.

**Comment by dhvcc** [comment]
I've fixed linting issues and added docstring flake ispection so it run in pre-commit stage. Please, mind fast-forwarding this branch `BBArikL/master` of this upstream into your PR. Thanks for your contribution!

**Comment by BBArikL** [comment]
I do not know how you can customize Codacy but I think D203 should be ignored, see https://github.com/PyCQA/pydocstyle/issues/141

**Pull request merged**
