### PR TITLE
Try to fix that 'item' in 'channel' with only one entry was not correctly converted to a list but instead dict

### PR DESCRIPTION
**Pull request by Fitmtfk**
Try to fix that 'item' in 'channel' with only one entry was not correctly converted to a list but instead dict

### CODE REVIEW

**Comment by dhvcc** [comment]
Hey, although it's kind of an intended behavior with the https://github.com/dhvcc/rss-parser#xmltodict, but yeah, having a model specify items as list but having a dict is a problem. I'm thinking about a sort of `OnlyList` type in `models.types` directory which will be a list subclass and convert dict to a list (but only dict, because we want to fail fast if anything happens)
We'll also need a test for that. Let me know what you think about it and if you'd like to implement it

**Comment by Fitmtfk** [comment]
You are right ,that is a more fundamental solution to the problem.

When I using this module processing some RSS get from same website,some work well, while others encounter problems.
And I find that when there is only one item in channel,it cause problem.
If I weren't in such a hurry to get it,  I wouldn't have encountered this problem.
It will have two entries next week.At that time, it will be processed correctly as a list.
You can know from my code that I only have very basic programming skills.
So I only fixed the problem I encountered using a not elegant method.
When there is only one item in channel,it should be processed as a list with only one dict.

**Comment by dhvcc** [comment]
If there are any troubles with RSS feeds using this lib - feel free to raise an issue, we'll see what the problem is and perhaps it's an issue with the code, which I'd love to fix, because I know that not all of the people that have issues will raise them and I'm aiming for this library to just work without needing to hack stuff. I'll implement the solution then and will reference this issue in a PR, will let you know when it's done
Thanks for using the library though :)

**Comment by Fitmtfk** [comment]
This library helps me a lot.I use this for several month.
Thank you for creating and maintaining this project :)

**Comment by dhvcc** [comment]
It's a pretty easy fix, but python3.8 is holding it back... will see what can be done

**Comment by dhvcc** [comment]
Finally fully fixed in [v1.2.1](https://github.com/dhvcc/rss-parser/releases/tag/v1.2.1)

**Pull request closed without merging**
