### PR TITLE
Prepare rss-parser for v0.2.4

### PR DESCRIPTION
**Pull request by BBArikL**
- Update black requirement to 22.3.0 (fixes pre-commit crash)
- Make parser more straightforward to the end user.

### CODE REVIEW

**Comment by BBArikL** [comment]
I also made a simple rss generator so you can create and debug or even create tests more easily. I have not included it in the  commits but I will include them in here:
generate_rss.py:
```
from datetime import datetime, timedelta
import xml.etree.ElementTree as ET

xmlt = ET.Element('rss')
xmlt.set('version', '2.0')

channel = ET.SubElement(xmlt, 'channel')
ET.SubElement(channel, 'title').text = 'RSS feed autogenerated'
ET.SubElement(channel, 'description').text = 'This is a description of the RSS feed.'
ET.SubElement(channel, 'language').text = 'English'

for i in range(1, 10):
    item = ET.SubElement(channel, 'item')
    ET.SubElement(item, 'title').text = f"Item #{i}"
    ET.SubElement(item, 'link').text = 'https://github.com/dhvcc/rss-parser'
    ET.SubElement(item, 'pubDate').text = (datetime(year=2000, month=1, day=1, hour=1,
                                                    minute=1, second=1, microsecond=0) +
                                           (i - 1) * (timedelta(days=1))).strftime(
        "%a, %d %b %Y %H:%M:%S %Z")
    ET.SubElement(item, 'category').text = f'The {i}th category.'
    # Should add img and href tags to test description_link and description_images
    ET.SubElement(item, 'description').text = f"This is the {i}th description."
    # Should add enclosure and itunes to test
    ET.SubElement(item, 'author').text = "dhvcc"

xmlb = ET.tostring(xmlt)

with open('generated.xml', 'wb') as f:
    f.write(xmlb)
```

test.py:
```
from rss_parser import Parser

rss_file = open('generated.xml', 'rt')
rss = rss_file.read()
rss_file.close()

feed = Parser(rss).parse(entries=['author'])

print(feed.title)
print(feed.version)
print(feed.language)
print(feed.description)

for item in feed.feed:
    print(item.title)
    print(item.enclosure)
    print(item.description)
    print(item.description_links)
    print(item.description_images)
    print(item.category)
    print(item.itunes)
    print(item.publish_date)
    print(item.link)
    print(item.other["author"])
``

**Comment by BBArikL** [comment]
Ok I give up Codacy https://stackoverflow.com/questions/45990301/pep257-d212-and-d213-conflicts

**Comment by dhvcc** [comment]
So:
1. I'd advise you to create PRs from new branches that branches from master, not your fork's master.
2. I've ignored Codacy's issue
3. I'll update black's version in a separate chuck of work.

Also there's a question. Did **only** hide methods that will **not need** to be used by end user?
@BBArikL

**Comment by BBArikL** [comment]
hey!
1. So you prefer that I restart my pr from the feature-meta branch?
2. Okay
3. All right.

For methods: When the end user wants to use autocomplete, method get_none(), get_text() and get_soup() get in the way of parse(). This is a minor aestethic change for the end user but it does affect multiple internal lines, so if you prefer that I start fresh a new pr, I will only keep the doc change of parse() and let you decide if you want to touch the other methods. 👍

**Comment by dhvcc** [comment]
> hey!
> 
> 1. So you prefer that I restart my pr from the feature-meta branch?
> 2. Okay
> 3. All right.
> 
> For methods: When the end user wants to use autocomplete, method get_none(), get_text() and get_soup() get in the way of parse(). This is a minor aestethic change for the end user but it does affect multiple internal lines, so if you prefer that I start fresh a new pr, I will only keep the doc change of parse() and let you decide if you want to touch the other methods. 👍

Don't recreate the PR. I get the idea, but the question is are we sure those methods won't be used by user? That's a yes or no and I'll merge this PR
Thanks for your contribution!

**Comment by BBArikL** [comment]
Hey, I get what you are saying. After giving it some though, some people might well use those methods since it can interface with getting themselves the raw BeautifulSoup object they want and check_none could be used to validate the output of the parser. I would then suggest adding full documentation to the methods (and maybe to the class too), so the library can have another feature worth a new release.

**Comment by dhvcc** [comment]
Sure, documentation is good too. I was thinking of adding proper docs, but I barely have time to work on this library. So, if you're thinking of raising a PR for it - would be nice

**Comment by dhvcc** [comment]
I'll close this PR as I think we agreed on something a bit different

**Pull request closed without merging**
